// 100个最常用法语动词
const verbs = [
  { id: 1, french: "acheter", chinese: "买", example: "J'ai acheté une baguette.", exampleZh: "我买了一条法国面包。", type: "er", irregular: false },
  { id: 2, french: "aider", chinese: "帮忙", example: "Pouvez-vous m'aider?", exampleZh: "你可以帮我吗？", type: "er", irregular: false },
  { id: 3, french: "aimer", chinese: "爱", example: "Je t'aime.", exampleZh: "我爱你。", type: "er", irregular: false },
  { id: 4, french: "appeler", chinese: "叫", example: "Je m'appelle Lou.", exampleZh: "我的名叫露。", type: "er", irregular: true },
  { id: 5, french: "apprendre", chinese: "学", example: "J'apprends le français.", exampleZh: "我在学法文。", type: "re", irregular: false },
  { id: 6, french: "arrêter", chinese: "停止", example: "Arrêtez de faire du bruit!", exampleZh: "不要再制造噪音了！", type: "er", irregular: false },
  { id: 7, french: "arriver", chinese: "到达", example: "On va arriver bientôt.", exampleZh: "我们快到了。", type: "er", irregular: false },
  { id: 8, french: "attendre", chinese: "等", example: "Attendez-moi!", exampleZh: "等等我！", type: "re", irregular: false },
  { id: 9, french: "boire", chinese: "喝", example: "Je bois du café tous les matins.", exampleZh: "我每天早上喝咖啡。", type: "re", irregular: true },
  { id: 10, french: "choisir", chinese: "选择", example: "J'ai choisi de rester.", exampleZh: "她选择留下。", type: "ir", irregular: false },
  { id: 11, french: "commencer", chinese: "开始", example: "Je commence à apprendre le français.", exampleZh: "我开始学法文。", type: "er", irregular: false },
  { id: 12, french: "compter", chinese: "计算;依赖", example: "Je compte sur toi!", exampleZh: "我就靠你了！", type: "er", irregular: false },
  { id: 13, french: "comprendre", chinese: "了解", example: "Je ne comprends pas.", exampleZh: "我不懂。", type: "re", irregular: false },
  { id: 14, french: "connaître", chinese: "认识", example: "Tu connais Claire?", exampleZh: "你认识克莱儿吗？", type: "re", irregular: true },
  { id: 15, french: "continuer", chinese: "继续", example: "Je continue à travailler.", exampleZh: "我继续工作。", type: "er", irregular: false },
  { id: 16, french: "croire", chinese: "相信", example: "Je ne crois pas.", exampleZh: "我不相信。", type: "re", irregular: true },
  { id: 17, french: "se coucher", chinese: "睡下", example: "Je vais me coucher.", exampleZh: "我要去睡了。", type: "pronominal", irregular: false },
  { id: 18, french: "demander", chinese: "问", example: "Demande à ta mère.", exampleZh: "去问你妈。", type: "er", irregular: false },
  { id: 19, french: "descendre", chinese: "下", example: "Je descends à la prochaine gare.", exampleZh: "我在下一站下车。", type: "re", irregular: false },
  { id: 20, french: "devoir", chinese: "必须", example: "Je dois partir maintenant.", exampleZh: "我现在得走了。", type: "re", irregular: true },
  { id: 21, french: "discuter", chinese: "讨论", example: "Je veux discuter avec toi.", exampleZh: "我想跟你讨论一下。", type: "er", irregular: false },
  { id: 22, french: "dire", chinese: "说", example: "Qu'est-ce que tu as dit?", exampleZh: "你刚刚说什么？", type: "re", irregular: true },
  { id: 23, french: "donner", chinese: "给", example: "Donne-moi ton numéro.", exampleZh: "给我你的号码。", type: "er", irregular: false },
  { id: 24, french: "dormir", chinese: "睡觉", example: "Tu dors?", exampleZh: "你在睡觉吗？", type: "ir", irregular: true },
  { id: 25, french: "se doucher", chinese: "洗澡", example: "Je vais me doucher.", exampleZh: "我要去洗澡。", type: "pronominal", irregular: false },
  { id: 26, french: "écrire", chinese: "写", example: "J'ai écrit une lettre à mon ami.", exampleZh: "我给我朋友写了封信。", type: "re", irregular: true },
  { id: 27, french: "écouter", chinese: "听", example: "Quel genre de musique écoutes-tu?", exampleZh: "你听哪种音乐？", type: "er", irregular: false },
  { id: 28, french: "emprunter", chinese: "借", example: "Il m'a emprunté de l'argent.", exampleZh: "他跟我借钱。", type: "er", irregular: false },
  { id: 29, french: "entendre", chinese: "听见", example: "Tu m'entends?", exampleZh: "你听得见我（说话）吗？", type: "re", irregular: false },
  { id: 30, french: "entrer", chinese: "进入", example: "Puis-je entrer?", exampleZh: "我可以进来吗？", type: "er", irregular: false },
  { id: 31, french: "envoyer", chinese: "寄送", example: "Je voudrais envoyer ce paquet.", exampleZh: "我想要寄这个包裹。", type: "er", irregular: true },
  { id: 32, french: "essayer", chinese: "试", example: "Puis-je essayer la taille 9?", exampleZh: "我能试试9号吗？", type: "er", irregular: false },
  { id: 33, french: "étudier", chinese: "学习", example: "J'étudie la littérature en France.", exampleZh: "我在法国读文学。", type: "er", irregular: false },
  { id: 34, french: "expliquer", chinese: "解释", example: "Pouvez-vous m'expliquer pourquoi?", exampleZh: "你可以跟我解释为什么吗？", type: "er", irregular: false },
  { id: 35, french: "falloir", chinese: "需要", example: "Il faut faire encore plus.", exampleZh: "我们需要做更多。", type: "re", irregular: true },
  { id: 36, french: "faire", chinese: "做", example: "Je fais du yoga.", exampleZh: "我做瑜珈。", type: "re", irregular: true },
  { id: 37, french: "finir", chinese: "完成", example: "J'ai fini mes devoirs.", exampleZh: "我写完了作业。", type: "ir", irregular: false },
  { id: 38, french: "gagner", chinese: "赢得", example: "On gagne de 2 points.", exampleZh: "我们得了2分。", type: "er", irregular: false },
  { id: 39, french: "habiter", chinese: "住", example: "Vous habitez où? J'habite à Taipei.", exampleZh: "你住在哪里？我住在台北。", type: "er", irregular: false },
  { id: 40, french: "s'habituer", chinese: "习惯", example: "Je ne suis pas habitué à ça.", exampleZh: "我不习惯这个。", type: "pronominal", irregular: false },
  { id: 41, french: "s'inquiéter", chinese: "担心", example: "T'inquiète pas.", exampleZh: "别担心。", type: "pronominal", irregular: false },
  { id: 42, french: "interdire", chinese: "禁止", example: "C'est interdit de fumer ici.", exampleZh: "这里禁止吸烟。", type: "re", irregular: false },
  { id: 43, french: "s'intéresser", chinese: "有兴趣", example: "Ça t'intéresse ou pas?", exampleZh: "这你有兴趣吗？", type: "pronominal", irregular: false },
  { id: 44, french: "jeter", chinese: "丢", example: "Je le jette à la poubelle.", exampleZh: "我把它丢到垃圾桶。", type: "er", irregular: true },
  { id: 45, french: "jouer", chinese: "玩", example: "Il joue au football.", exampleZh: "他踢足球。", type: "er", irregular: false },
  { id: 46, french: "laisser", chinese: "放", example: "Laisse-moi tranquille.", exampleZh: "别管我/让我静一静。", type: "er", irregular: false },
  { id: 47, french: "se lever", chinese: "起来", example: "Je me suis levé tôt ce matin.", exampleZh: "我今天早上很早起来。", type: "pronominal", irregular: false },
  { id: 48, french: "lire", chinese: "读", example: "J'aime lire des romans.", exampleZh: "我喜欢看小说。", type: "re", irregular: true },
  { id: 49, french: "manger", chinese: "吃", example: "J'ai mangé un pain au chocolat.", exampleZh: "我吃了一个巧克力面包。", type: "er", irregular: false },
  { id: 50, french: "manquer", chinese: "缺少", example: "Tu me manques.", exampleZh: "我想你。", type: "er", irregular: false },
  { id: 51, french: "mettre", chinese: "戴;做", example: "Je mets un chapeau.", exampleZh: "我戴上一顶帽子。", type: "re", irregular: true },
  { id: 52, french: "montrer", chinese: "展示", example: "Je vais te montrer.", exampleZh: "我会展示给你看。", type: "er", irregular: false },
  { id: 53, french: "se moquer", chinese: "嘲笑", example: "Il se moque de moi.", exampleZh: "他嘲笑我。", type: "pronominal", irregular: false },
  { id: 54, french: "obtenir", chinese: "获得", example: "Tu obtiens un bonus.", exampleZh: "你获得一项红利。", type: "re", irregular: false },
  { id: 55, french: "s'occuper", chinese: "关心", example: "Je m'occupe de toi.", exampleZh: "我照顾你。", type: "pronominal", irregular: false },
  { id: 56, french: "offrir", chinese: "提供", example: "Il m'offre un cadeau.", exampleZh: "他给我一个礼物。", type: "re", irregular: false },
  { id: 57, french: "oublier", chinese: "忘记", example: "J'ai oublié de te dire.", exampleZh: "我忘了告诉你。", type: "er", irregular: false },
  { id: 58, french: "ouvrir", chinese: "打开", example: "Ouvrez la fenêtre, s'il vous plaît.", exampleZh: "请把窗户打开。", type: "re", irregular: false },
  { id: 59, french: "parler", chinese: "说话", example: "Je parle anglais et chinois.", exampleZh: "我说英文和中文。", type: "er", irregular: false },
  { id: 60, french: "participer", chinese: "参加", example: "Je dois participer à la réunion.", exampleZh: "我必须参加会议。", type: "er", irregular: false },
  { id: 61, french: "partir", chinese: "离开", example: "Je pars demain.", exampleZh: "我明天离开。", type: "re", irregular: false },
  { id: 62, french: "prendre", chinese: "拿", example: "Je prends un café.", exampleZh: "我喝咖啡。", type: "re", irregular: true },
  { id: 63, french: "penser", chinese: "想", example: "Je pense à toi.", exampleZh: "我在想你。", type: "er", irregular: false },
  { id: 64, french: "perdre", chinese: "失去", example: "J'ai perdu mon portable.", exampleZh: "我遗失了我的手机。", type: "re", irregular: false },
  { id: 65, french: "pouvoir", chinese: "可以", example: "Je peux vous aider?", exampleZh: "我可以帮你吗？", type: "re", irregular: true },
  { id: 66, french: "préférer", chinese: "更喜欢", example: "Je préfère le vin rouge.", exampleZh: "我更喜欢红酒。", type: "er", irregular: false },
  { id: 67, french: "prêter", chinese: "借", example: "Il m'a prêté de l'argent.", exampleZh: "他借了我一些钱。", type: "er", irregular: false },
  { id: 68, french: "promettre", chinese: "答应", example: "Je te promets.", exampleZh: "我答应你。", type: "re", irregular: false },
  { id: 69, french: "proposer", chinese: "提供", example: "Je te propose un choix.", exampleZh: "我给你一个选择。", type: "er", irregular: false },
  { id: 70, french: "raconter", chinese: "描述", example: "Je raconte une histoire.", exampleZh: "我讲一个故事。", type: "er", irregular: false },
  { id: 71, french: "recevoir", chinese: "收到", example: "J'ai reçu un e-mail.", exampleZh: "我收到一封邮件。", type: "re", irregular: false },
  { id: 72, french: "réfléchir", chinese: "思考", example: "Je vais réfléchir.", exampleZh: "我考虑一下。", type: "ir", irregular: false },
  { id: 73, french: "refuser", chinese: "拒绝", example: "Je refuse de croire.", exampleZh: "我拒绝相信。", type: "er", irregular: false },
  { id: 74, french: "regarder", chinese: "看", example: "Je regarde un programme de télévision.", exampleZh: "我在看一个电视节目。", type: "er", irregular: false },
  { id: 75, french: "remercier", chinese: "感谢", example: "Je vous remercie pour votre aide.", exampleZh: "谢谢你的帮助。", type: "er", irregular: false },
  { id: 76, french: "rencontrer", chinese: "遇见", example: "Je suis content de vous rencontrer.", exampleZh: "我很高兴遇到你。", type: "er", irregular: false },
  { id: 77, french: "rendre", chinese: "归还", example: "J'ai rendu le livre.", exampleZh: "我还了那本书。", type: "re", irregular: false },
  { id: 78, french: "rentrer", chinese: "回家", example: "Je suis rentré chez moi.", exampleZh: "我回到家。", type: "re", irregular: false },
  { id: 79, french: "répondre", chinese: "回复", example: "S'il vous plaît répondre dès que possible.", exampleZh: "请尽速回复。", type: "re", irregular: false },
  { id: 80, french: "se reposer", chinese: "休息", example: "Je me repose à la maison.", exampleZh: "我在家休息。", type: "pronominal", irregular: false },
  { id: 81, french: "rester", chinese: "停留", example: "Je reste au lit.", exampleZh: "我仍在床上。", type: "er", irregular: false },
  { id: 82, french: "réussir", chinese: "成功", example: "Tu vas réussir.", exampleZh: "你会成功的。", type: "ir", irregular: false },
  { id: 83, french: "rêver", chinese: "梦见", example: "J'ai rêvé de toi.", exampleZh: "我梦见你了。", type: "er", irregular: false },
  { id: 84, french: "rire", chinese: "笑", example: "Tout le monde s'est mis à rire.", exampleZh: "大家都笑了起来。", type: "re", irregular: true },
  { id: 85, french: "savoir", chinese: "知道", example: "Je sais pas.", exampleZh: "我不知道。", type: "re", irregular: true },
  { id: 86, french: "sembler", chinese: "似乎", example: "Il semble t'aimer.", exampleZh: "他似乎喜欢你。", type: "er", irregular: false },
  { id: 87, french: "sortir", chinese: "离开", example: "Je sors d'ici.", exampleZh: "我要离开这里。", type: "re", irregular: false },
  { id: 88, french: "souhaiter", chinese: "希望", example: "Je te souhaite une bonne journée.", exampleZh: "我祝你有美好的一天。", type: "er", irregular: false },
  { id: 89, french: "se souvenir", chinese: "记得", example: "Je ne me souviens plus.", exampleZh: "我不记得了。", type: "pronominal", irregular: false },
  { id: 90, french: "suivre", chinese: "跟随", example: "Suivez-moi.", exampleZh: "跟我来。", type: "re", irregular: false },
  { id: 91, french: "téléphoner", chinese: "打电话", example: "J'ai téléphoné à mon papa.", exampleZh: "我打了电话给我爸。", type: "er", irregular: false },
  { id: 92, french: "tenir", chinese: "拿", example: "Tiens moi au courant.", exampleZh: "再跟我说（之后怎样）。", type: "re", irregular: false },
  { id: 93, french: "traduire", chinese: "翻译", example: "Pouvez-vous traduire cela pour moi?", exampleZh: "你可以帮我翻译这个吗？", type: "re", irregular: false },
  { id: 94, french: "travailler", chinese: "工作", example: "Je travaille de la maison.", exampleZh: "我在家工作。", type: "er", irregular: false },
  { id: 95, french: "se tromper", chinese: "搞错", example: "Je me suis trompé.", exampleZh: "我搞错了。", type: "pronominal", irregular: false },
  { id: 96, french: "vendre", chinese: "销售", example: "J'ai vendu ma voiture.", exampleZh: "我卖了我的车子。", type: "re", irregular: false },
  { id: 97, french: "venir", chinese: "来", example: "Viens ici avec moi.", exampleZh: "来这边和我一起。", type: "re", irregular: true },
  { id: 98, french: "voir", chinese: "看", example: "Est-ce que tu me vois?", exampleZh: "你看到我了吗？", type: "re", irregular: true },
  { id: 99, french: "vouloir", chinese: "想要", example: "Je veux le savoir.", exampleZh: "我想要知道。", type: "re", irregular: true },
  { id: 100, french: "voyager", chinese: "旅行", example: "Je voyage en train.", exampleZh: "我搭火车旅行。", type: "er", irregular: false },
  { id: 104, french: "visiter", chinese: "参观;访问", example: "Je visite Paris.", exampleZh: "我参观巴黎。", type: "er", irregular: false },
  { id: 105, french: "déménager", chinese: "搬家", example: "Je déménage demain.", exampleZh: "我明天搬家。", type: "er", irregular: false },
  { id: 106, french: "vivre", chinese: "生活;生存", example: "Je vis à Paris.", exampleZh: "我住在巴黎。", type: "re", irregular: true }
];

// 添加 être 和 avoir（最常用的两个动词）
const essentialVerbs = [
  { id: 101, french: "être", chinese: "是", example: "Je suis étudiant.", exampleZh: "我是学生。", type: "re", irregular: true },
  { id: 102, french: "avoir", chinese: "有", example: "J'ai un chat.", exampleZh: "我有一只猫。", type: "re", irregular: true },
  { id: 103, french: "aller", chinese: "去", example: "Je vais à l'école.", exampleZh: "我去学校。", type: "er", irregular: true }
];

// 合并所有动词
const allVerbs = [...essentialVerbs, ...verbs];
